version: "1"

services:
  - type: web
    name: driftguard
    env: docker
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: driftguard-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false

databases:
  - name: driftguard-db
    databaseName: driftguard
    user: driftguard
